import { NamedNode, sym } from 'rdflib'
import SolidFileClient from 'solid-file-client'
import { ACL_LINK } from '../acl/aclLogic'
import { ns } from '../util/ns'
import { assertSuccessfulHttpResponse, isMissingError } from './resourceHttp'
import { readWacAccessInfo } from './resourceMetadata'
import { type AclLogic, type AuthnLogic, type ProfileLogic, type ResourceAccess, type ResourceDeleteOptions, type ResourceLogic, type ResourceMetadata, type TypeIndexLogic, type TypeIndexScope, type TypeIndexVisibility } from '../types'

export function createResourceLogic(store, authn: AuthnLogic, aclLogic: AclLogic, containerLogic, typeIndexLogic: TypeIndexLogic, profileLogic: ProfileLogic): ResourceLogic {
  // need to look at the code below this was generated by AI
  // to fix a problem i had.
  const sessionAny = authn.authSession as any
  const authAdapter = {
    fetch: (typeof sessionAny.fetch === 'function'
      ? sessionAny.fetch.bind(sessionAny)
      : typeof sessionAny.authFetch === 'function'
        ? sessionAny.authFetch.bind(sessionAny)
        : globalThis.fetch.bind(globalThis))
  }

  const solidFileClient = new SolidFileClient(authAdapter)
  const metadataCache = new Map<string, Promise<ResourceMetadata>>()

  function createContainer(url: string) {
    return containerLogic.createContainer(url)
  }

  function isContainer(resourceNode: NamedNode) {
    return containerLogic.isContainer(resourceNode)
  }

  function isStorageRoot(resourceStore: typeof store, resourceNode: NamedNode) {
    return containerLogic.isStorageRoot(resourceStore, resourceNode)
  }

  function noHiddenFiles(resourceNode: NamedNode) {
    return containerLogic.noHiddenFiles(resourceNode)
  }

  function canAcceptUploads(resourceNode: NamedNode) {
    return !hasMintClassIndexDocument(resourceNode)
  }

  function getContainerVisibleItemCount(resourceNode: NamedNode) {
    return containerLogic.getContainerVisibleItemCount(resourceNode)
  }

  function getContainerIndexThing(containerNode: NamedNode) {
    return containerLogic.getContainerIndexThing(containerNode)
  }

  function getContainerMintClass(containerNode: NamedNode) {
    return containerLogic.getContainerMintClass(containerNode)
  }

  async function loadContainerMintClass(containerNode: NamedNode) {
    if (!isContainer(containerNode)) {
      return undefined
    }

    const indexThing = getContainerIndexThing(containerNode)
    try {
      await store.fetcher.load(indexThing.doc())
    } catch (_error) {
      // Best-effort: if the index document cannot be loaded, fall back to the cache.
    }

    return getContainerMintClass(containerNode)
  }

  function hasMintClassIndexDocument(resourceNode: NamedNode) {
    return containerLogic.hasMintClassIndexDocument(resourceNode)
  }

  function isPaneIndexDocument(resourceNode: NamedNode) {
    return resourceNode.uri.endsWith('/index.ttl#this') || resourceNode.uri.endsWith('index.ttl#this')
  }

  async function getTypeIndexScopeForCurrentUser(visibility: TypeIndexVisibility, createMissingLinks: boolean): Promise<TypeIndexScope | null> {
    const currentUser = authn.currentUser()
    if (!currentUser) {
      return null
    }

    const scopes = createMissingLinks
      ? await typeIndexLogic.loadTypeIndexesFor(currentUser)
      : await typeIndexLogic.loadExistingTypeIndexesFor(currentUser)

    return scopes.find(scope => scope.label === visibility) ?? null
  }

  async function findTypeIndexRegistrations(resource: NamedNode, visibility: TypeIndexVisibility): Promise<NamedNode[]> {
    const scope = await getTypeIndexScopeForCurrentUser(visibility, false)
    if (!scope) {
      return []
    }

    return typeIndexLogic.findTypeIndexRegistrationsForResourceInScope(resource, scope)
  }

  async function addToTypeIndex(resource: NamedNode, visibility: TypeIndexVisibility, theClass: NamedNode): Promise<NamedNode | null> {
    const scope = await getTypeIndexScopeForCurrentUser(visibility, true)
    if (!scope) {
      throw new Error(`Unable to find ${visibility} type index for the current user`)
    }

    const existingRegistrations = typeIndexLogic.findTypeIndexRegistrationsForResourceInScope(resource, scope)
    if (existingRegistrations.length > 0) {
      return existingRegistrations[0]
    }

    return typeIndexLogic.registerInTypeIndex(resource, scope.index, theClass)
  }

  async function removeFromTypeIndex(resource: NamedNode, visibility: TypeIndexVisibility): Promise<boolean> {
    const scope = await getTypeIndexScopeForCurrentUser(visibility, false)
    if (!scope) {
      return false
    }

    return typeIndexLogic.deleteTypeIndexRegistrationsForResourceInScope(resource, scope)
  }

  function readMetadata(subject: NamedNode, response: Response): ResourceMetadata {
    let contentType: string | undefined
    let canEdit = false
    let canControl = false
    let isPublic = false
    let canDelete = false
    let eTag: string | undefined
    let modified: string | undefined

    if (response.headers) {
      const contentTypeHeader = response.headers.get('content-type')
      contentType = contentTypeHeader?.split(';')[0] ?? undefined

      const accessFlags = readWacAccessInfo(response.headers.get('wac-allow'))
      canEdit = accessFlags.canEdit
      canControl = accessFlags.canControl
      isPublic = accessFlags.isPublic
      eTag = response.headers.get('etag') ?? undefined
      modified = store.anyValue(subject as any, ns.dct('modified')) || store.anyValue(subject as any, ns.dc('modified')) || undefined
    }

    if ((!response.headers || !response.headers.get('content-type')) && (!response.headers || !response.headers.get('wac-allow') || !response.headers.get('etag'))) {
      const reqs = store.each(
        null,
        store.sym('http://www.w3.org/2007/ont/link#requestedURI'),
        subject
      )
      reqs.map((req: any) => {
        const responseNode = store.any(
          req as any,
          store.sym('http://www.w3.org/2007/ont/link#response')
        )
        if (responseNode && responseNode.termType === 'NamedNode') {
          const responseContentType = store.anyValue(responseNode as any, ns.httph('content-type')) || undefined
          if (contentType === undefined) {
            contentType = responseContentType
          }
          const wacAllow = (store.anyValue(responseNode as any, ns.httph('wac-allow')) as string | undefined) ||
            (store.anyValue(responseNode as any, ns.httph('WAC-Allow')) as string | undefined)
          const accessFlags = readWacAccessInfo(wacAllow)
          canEdit = canEdit || accessFlags.canEdit
          canControl = canControl || accessFlags.canControl
          isPublic = isPublic || accessFlags.isPublic
          const responseETag = store.anyValue(responseNode as any, ns.httph('etag')) || undefined
          if (eTag === undefined) {
            eTag = responseETag
          }
          modified = store.anyValue(subject as any, ns.dct('modified')) || store.anyValue(subject as any, ns.dc('modified')) || undefined
        }
      })
    }

    const aclUri = store.any(subject, ACL_LINK)?.value || undefined
    const access: ResourceAccess = { canEdit, canControl, isPublic, canDelete }
    return { contentType, access, aclUri, eTag, modified }
  }

  async function fetchHeadMetadata(subject: NamedNode): Promise<ResourceMetadata> {
    const response = await store.fetcher.webOperation('HEAD', subject.uri)
    assertSuccessfulHttpResponse(response, 'HEAD')
    return readMetadata(subject, response)
  }

  async function userCanWriteToContainingContainer(resourceNode: NamedNode): Promise<boolean> {
    const containerNode = store.any(resourceNode, ns.ldp('contains')) || resourceNode.dir()
    if (!containerNode || containerNode.termType !== 'NamedNode') {
      return false
    }

    try {
      const containerMetadata = await fetchHeadMetadata(containerNode as NamedNode)
      return containerMetadata.access.canEdit
    } catch (_error) {
      return false
    }
  }

  async function userCanDeleteResource(resourceNode: NamedNode): Promise<boolean> {
    return userCanWriteToContainingContainer(resourceNode)
  }

  async function fetchMetadata(subject: NamedNode): Promise<ResourceMetadata> {
    const cachedMetadata = metadataCache.get(subject.uri)
    if (cachedMetadata) {
      return cachedMetadata
    }

    const metadataPromise = (async () => {
    let resourceMetadata: ResourceMetadata

      try {
        resourceMetadata = await fetchHeadMetadata(subject)
      } catch (_error) {
        resourceMetadata = {
          contentType: undefined,
          access: { canEdit: false, canControl: false, isPublic: false, canDelete: false },
          aclUri: undefined,
          eTag: undefined,
          modified: undefined
        }
      }

      const canDelete = await userCanDeleteResource(subject)
      return {
        ...resourceMetadata,
        access: {
          ...resourceMetadata.access,
          canDelete
        }
      }
    })()

    metadataCache.set(subject.uri, metadataPromise)

    return metadataPromise
  }

  async function deleteTypeIndexesForResource(resourceNode: NamedNode, user?: NamedNode | null) {
    if (!user) return

    try {
      await typeIndexLogic.deleteTypeIndexRegistrationForResource(resourceNode, user)
    } catch (_error) {
      // Keep resource deletion best-effort even if type-index cleanup fails.
    }
  }

  async function recursiveDelete(resourceNode: NamedNode, options: ResourceDeleteOptions = {}) {
    const resourceParent = resourceNode.dir()

    if (isContainer(resourceNode)) {
      const containerMembers = await containerLogic.getContainerMembers(resourceNode)
      await Promise.all(containerMembers.map((url) => recursiveDelete(sym(url), options)))
    }

    let deleted
    try {
      deleted = await store.fetcher._fetch(resourceNode.value, { method: 'DELETE' })
      assertSuccessfulHttpResponse(deleted, 'DELETE', { allowNotFound: true })
    } catch (error) {
      if (!isMissingError(error)) {
        throw error
      }
    }

    if (options.deleteTypeIndexes) {
      await deleteTypeIndexesForResource(resourceNode, authn.currentUser())
    }

    if (resourceParent) {
      store.removeMatches(resourceParent, ns.ldp('contains'), resourceNode, resourceParent.doc())
    }

    store.removeDocument(resourceNode)
    store.fetcher.unload(resourceNode.doc())
    return deleted
  }

  async function deleteResourceAndTypeIndexIfExists(resourceNode: NamedNode) {
    await recursiveDelete(resourceNode, { deleteTypeIndexes: true })
  }

  async function ensureTrashContainerForCurrentUser(): Promise<NamedNode> {
    const currentUser = authn.currentUser()

    if (!currentUser) {
      throw new Error('Cannot move resource to trash without a current user')
    }

    const podRoot = profileLogic.getPodRoot(currentUser)
    const podRootUri = podRoot.uri.endsWith('/') ? podRoot.uri : podRoot.uri + '/'
    const trashContainer = store.sym(`${podRootUri}Trash/`)

    try {
      await store.fetcher.webOperation('HEAD', trashContainer.uri)
    } catch (_error) {
      await createContainer(trashContainer.uri)
    }

    try {
      // Keep Trash owner-only; do not grant public access.
      await aclLogic.setACLUserOwnerOnly(trashContainer.uri, currentUser, { defaultForNew: true })
    } catch (error) {
      // Add error handling
    }

    return trashContainer
  }

  async function moveToTrash(resourceNode: NamedNode) {
    const trashContainer = await ensureTrashContainerForCurrentUser()
    const resourceParent = resourceNode.dir()
    const resourceUri = resourceNode.uri.endsWith('/') ? resourceNode.uri.slice(0, -1) : resourceNode.uri
    const resourceName = resourceUri.substring(resourceUri.lastIndexOf('/') + 1)
    const targetUrl = resourceNode.termType === 'NamedNode' && isContainer(resourceNode)
      ? `${trashContainer.uri}${resourceName}/`
      : `${trashContainer.uri}${resourceName}`

    // TODO: Revisit type-index cleanup for Trash moves after confirming the
    // correct rule for index.ttl and container registrations.
    await moveResource(resourceNode, targetUrl)

    const sourceStillExists = await solidFileClient.itemExists(resourceNode.uri).catch((_error) => false)

    if (sourceStillExists) {
      await recursiveDelete(resourceNode)
    }

    if (resourceParent) {
      store.removeMatches(resourceParent, ns.ldp('contains'), resourceNode, resourceParent.doc())
    }

    store.removeDocument(resourceNode)
    store.fetcher.unload(resourceNode.doc())

    const containersToReload = [resourceParent, trashContainer].filter(
      (container): container is NamedNode => Boolean(container)
    )

    await Promise.all(containersToReload.map(async (container) => {
      metadataCache.delete(container.uri)

      try {
        await store.fetcher.load(container, { force: true, clearPreviousData: true })
      } catch (_error) {
        // The move succeeded; keep the local store usable if reconciliation fails.
      }
    }))

    const targetNode = sym(targetUrl)
    if (!store.holds(trashContainer, ns.ldp('contains'), targetNode, trashContainer.doc())) {
      store.add(trashContainer, ns.ldp('contains'), targetNode, trashContainer.doc())
    }

    metadataCache.delete(resourceNode.uri)
    metadataCache.delete(targetNode.uri)
  }

  async function copyResource(resourceNode: NamedNode, targetUrl: string) {
    if (isContainer(resourceNode)) {
      await solidFileClient.copyFolder(resourceNode.uri, targetUrl)
      return
    }

    await solidFileClient.copyFile(resourceNode.uri, targetUrl)
  }

  async function moveResource(resourceNode: NamedNode, targetUrl: string) {
    // .acl and .meta sidecars are server-managed on many pods, so move the resource itself only.
    await solidFileClient.move(resourceNode.uri, targetUrl, { withAcl: false, withMeta: false })
  }

  return {
    recursiveDelete,
    deleteResourceAndTypeIndexIfExists,
    moveToTrash,
    fetchMetadata,
    createContainer,
    isContainer,
    isStorageRoot,
    noHiddenFiles,
    canAcceptUploads,
    getContainerVisibleItemCount,
    getContainerIndexThing,
    getContainerMintClass,
    loadContainerMintClass,
    hasMintClassIndexDocument,
    isPaneIndexDocument,
    findTypeIndexRegistrations,
    addToTypeIndex,
    removeFromTypeIndex,
    copyResource,
    moveResource
  }
}
